### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by mildsauceminds** [eBay/ebay-oauth-python-client#7]
Its a bit insane to me that we've got developers working on OAuth and they name packages "model"...  Oauth always seems to be a mess to work with. 

ANYWAYS, if anyone is having similar problems.  

NOTE I am running this in python3.

`python GetUserAccessToken.py`

Throws this error:

```
python GetUserAccessToken.py 
Traceback (most recent call last):
  File "GetUserAccessToken.py", line 22, in <module>
    from oauthclient.oauth2api import oauth2api
  File "../oauthclient/oauth2api.py", line 23, in <module>
    import model.util
ModuleNotFoundError: No module named 'model'
```

A few quick fixes I've tried:
```
pip3 install python-oauth2
pip3 install pyyaml==5.1.0
```

Doesn't seem to fix the problem.

**Comment by alexb2123** [comment]
same issue

**Comment by matecsaj** [comment]
The "Ported to python3" pull request includes a fix for this problem. [https://github.com/eBay/ebay-oauth-python-client/pull/6](https://github.com/eBay/ebay-oauth-python-client/pull/6)

**Comment by sachins301** [comment]
Was this fixed ? I'm stuck at this point. Is this a dead project?
